### ISSUE TITLE
cannot load special url with query argument

### ISSUE THREAD

**Issue by chinavane** [billmalarky/react-native-image-cache-hoc#12]
The plugin can load this image file,but can't load the url with argument.why?
http://ophkybhhb.bkt.clouddn.com/032e7596d4e7ed5cae43f9bd7215f93b2c801156.png

http://ophkybhhb.bkt.clouddn.com/032e7596d4e7ed5cae43f9bd7215f93b2c801156.png?imageView2/1/w/50/h/50/q/75|imageslim

**Comment by billmalarky** [comment]
The second url contains a | character.

[This is an invalid url character](https://stackoverflow.com/a/1547940/820273). It will need to be encoded in order to be valid.

I suggest using [encodeURIComponent()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent) on the query parameter to achieve this.
