### ISSUE TITLE
Unable to determine remote image filetype

### ISSUE THREAD

**Issue by kidasov** [billmalarky/react-native-image-cache-hoc#24]
When i try to load images with uri without file extension like _.png_ _.jpg_. i get this error. For example 
`https://s3.us-east-2.amazonaws.com/my-files/da10e0d5-a781-4601-b40e-304459fbbd61`
```
Error: Unable to determine remote image filetype.
    at FileSystem.getFileNameFromUrl$ (blob:http://localhost:8081/bdbc2931-ac7a-4ccf-babd-9e95180ae711:110388:23)
```

Any help will be highly appreciated. Anyway great package.

**Comment by billmalarky** [comment]
If your image server does not supply a file extension, it must supply a
standard content-type http header.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type

One of the above is required to determine image file type.

**Comment by snobear** [comment]
If you use Google Firebase storage to store your images, be sure you store the extension in the filename ref.  The content-type in the response headers when downloading gives you `application/json` even if you've supplied the proper mime type in the metadata when uploading. i.e. content-type headers with Firebase Storage are unreliable.

**Comment by colaskirschoff** [comment]
Hey @billmalarky  ! Nice to see that you're maintaining another nice lib :)

About this issue, if I understand well, as soon as the uri does not contain the extension the lib needs to make a call again to read it from the content type. It means that:
1 - It's still one call per image loading, which is costly if the photo provider is not free
2 - It does not work offline

I modified a bit the code so that the sha1 of the url is used as the folder name, where we store the photo with whatever extension was found in the content type. That way every time we need to load an image from an url the library can find it locally even when the extension is not included in it. 

Here is the resulting file tree for clarity:
<img width="450" alt="image" src="https://user-images.githubusercontent.com/9667205/48522238-30f6cb80-e878-11e8-875b-b63a29fcd904.png">

Not sure if it makes sense for your library, but at least it works the same way for uri that contain the extenstion or not !

Thanks for what you're doing in any case :)

**Comment by hasgardee** [comment]
@colaskirschoff could you please the changes you made in the library?

**Comment by lalit759** [comment]
I am also getting warning
Error: Unable to determine remote image filetype.
