### ISSUE TITLE
Warning on last version

### ISSUE THREAD

**Issue by khrizt** [billmalarky/react-native-image-cache-hoc#5]
Hi @billmalarky 

I've updated to the last library version and sometimes I get the following warning:

`TypeError: undefined is not a function (evaluating 'this.cancelLocalFilePathRequest()')`

Looks like sometimes the function is not initialized. It occurs when a view that has a ImageCacheHoc disappears quickly.

And btw, I have a question, the images that are stored in the cache (not permanently) should be visible from the DocumentDir folder? The problem is in a app screen that has a lot of images, I always get the placeholder but looking the code if it's a local file and already exists it should display the image directly from the local fs. But I don't know if it's the correct behaviour.

Thanks

**Comment by billmalarky** [comment]
I see what's happening.

this.cancelLocalFilePathRequest() is set in componentDidMount(), which fires after component finishes mounting (which is the correct place for this.cancelLocalFilePathRequest() to fire). The edge case is occurring when component begins mounting , but then is unmounted again before mounting completes, so componentWillUnmount() is getting called but componentDidMount() was never called.

I'll whip up a quick patch to check this.cancelLocalFilePathRequest is set before calling.

**Comment by billmalarky** [comment]
Patched & deployed: https://github.com/billmalarky/react-native-image-cache-hoc/commit/8b8bb9c19f9fd9765c47081abeaf981cda660072

**Comment by billmalarky** [comment]
> And btw, I have a question, the images that are stored in the cache (not permanently) should be visible from the DocumentDir folder? The problem is in a app screen that has a lot of images, I always get the placeholder but looking the code if it's a local file and already exists it should display the image directly from the local fs. But I don't know if it's the correct behaviour.

All image files are either stored in the DocumentDir (android) or the CacheDir (iOS). "Permanent" files are stored in {ROOT_DIR}/react-native-image-cache-hoc/permanent, "cache" files are stored in {ROOT_DIR}/react-native-image-cache-hoc/cache. On iOS, images stored in CacheDir are stored with a "do not back up" flag so iOS will not remove the files during its garbage collection process (see [here](https://github.com/wkh237/react-native-fetch-blob#user-content-cache-file-management) and [here](https://developer.apple.com/icloud/documentation/data-storage/index.html) -- note I could be misinformed, I'm clarifying [here](https://github.com/wkh237/react-native-fetch-blob/issues/126)).

If I had to guess, the app screen you are loading has so many images that you are going over the cache limit size with that one screen alone. So the cache files on the screen are getting pruned from the cache soon after they are built [1].

Example: cachePruneTriggerLimit defaults to 15MB. If you are loading 30 images onto one app screen and each image is exactly 1 MB, the first 15 images will be removed from the cache by the time the 30th image has loaded, so the next time the same page loads those 15 will have to be pulled from the network again. The solution is of course to simply [bump cachePruneTriggerLimit up to a significantly higher limit](https://github.com/billmalarky/react-native-image-cache-hoc#options), maybe 50 or 100 MB for example. It's a judgement call to decide how high you want cachePruneTriggerLimit to be, since a higher cachePruneTriggerLimit will mean better app performance, but also it will mean your app takes up more disk space and some users might not like that.

Note for your local testing, it may help to see the dir the files are being written to buy console logging this.baseFilePath in the FileSystem constructor [here](https://github.com/billmalarky/react-native-image-cache-hoc/blob/master/lib/FileSystem.js#L72).

Footnote:
1.) There's logic to ensure image files that are used by a currently mounted component will not be pruned from cache regardless of cache size, but the moment that component unmounts the related cache file is fair game for garbage collection.

**Comment by khrizt** [comment]
Wow, thanks for the speed answering and solving the issue! I'll take a look at the cache and images size, but theoretically the images are around 4KB. But there must be something I'm not doing correctly. Thanks man, I'll say something when I solve it.

**Comment by billmalarky** [comment]
Yes no problem.

Add that console.log of baseFilePath so you can actually watch the directory on your dev machine. Make sure the files are getting written to the cache folder, and see if they are being removed.

Just fyi, the placeholder will still render for a split second while the code hits your local disk to pull the image files. This is to be expected because there is a slight lag in time it takes to check that the image exists locally then load it into an <Image> component and render (we don't block while checking if the file exists on local disk of course :-). But the difference between loading from disk and loading from the network is huge, especially for larger image files.

Let me know if any weirdness stands out.

**Comment by khrizt** [comment]
It looks like everything is ok, I found all the images through the adb shell. 

By the way, in the case I told you where I have some images inside a FlatList I was thinking that maybe is a good idea to convert the Component to PureComponent to improve performance, do you think it's a good idea? I have the commit in my fork https://github.com/khrizt/react-native-image-cache-hoc/commit/5f731a445823952d4edee15b640053fa106401fa

**Comment by billmalarky** [comment]
I'm definitely open to the suggestion! I'll investigate when I get to the
office later today.

**Comment by khrizt** [comment]
Ok, let me know, I did some testing and it works perfectly, but the testing was not thorough.

**Comment by billmalarky** [comment]
Can you make a new issue "Feature Request: Implement PureComponent" so we can track this idea better?

**Comment by khrizt** [comment]
Done
